plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexa.xr'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nexa.xr'
        minSdk 26
        targetSdk 35
        versionCode 230401
        versionName '23.4.1-startup'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


dependencies {
    implementation "com.android.tools.build:apksig:8.7.3"
    androidTestImplementation "androidx.test:runner:1.6.2"
    androidTestImplementation "androidx.test.ext:junit:1.2.1"
}
